### ISSUE TITLE
summary html [enh]

### ISSUE THREAD

**Issue by PeerHerholz** [miykael/fmriflows#1]
Would you be interested in a summary html comparable to the [fmriprep one](http://fmriprep.readthedocs.io/en/latest/_static/sample_report.html) including the visualizations you're currently plotting/viewing in the notebooks? Not as an replacement for those, but rather as an  easy to check complementary add on or function? If so, I could work on that.

**Comment by miykael** [comment]
hey @PeerHerholz - so, I think I finally have the two preprocessing pipelines on a stable niveau. As you saw, there's a [report template](https://github.com/miykael/fmriflows/blob/master/scripts/templates/report_template.html) in the scripts/templates folder. I thought about creating all visualizations in the datasink (i.e. derivatives folder) and than have an report HTML linking to them (like FSL). I think fmriprep actually embedds the figures in the html. If you find out how to do that, that's of course also an option :-)

I would be very happy if you would want to work on a nice summary/report. I'm happy with the figures from the anatomy preproc pipeline:

**Tissue Segmentation of T1w**
![ses-01_segmentation](https://user-images.githubusercontent.com/950321/42126714-541a1df4-7c8c-11e8-879e-1def07c4d306.jpg)

**Brain Extraction of T1w**
![ses-01_brain](https://user-images.githubusercontent.com/950321/42126712-53db3fe4-7c8c-11e8-8276-43cf0d2b103f.jpg)

**T1w to MNI registration**
![ses-01_transform_warped](https://user-images.githubusercontent.com/950321/42126713-53fccd58-7c8c-11e8-9814-d7cb9690ff76.jpg)

But I struggle a lot with the outputs for the functional pipeline. You can find my attempts at the end of the [02_preproc_func.ipynb](https://github.com/miykael/fmriflows/blob/master/notebooks/02_preproc_func.ipynb) under `WIP: To show possible outputs`. I think the one that shows the corregistration, as well as the CompCorA and CompCorT masks is nice, but otherwise...
![task-multi_ses-01_run-01_overlays](https://user-images.githubusercontent.com/950321/42126725-748ded68-7c8c-11e8-9849-4f7054e6c560.jpg)

**Comment by miykael** [comment]
Please feel free to change everything! Even nodes in the pipeline etc.
For example, I'm not sure if it makes sense that I compute the correlation between the confounds and the functional image (kind of to see which voxels correlate with which confounds). In theory nice, but it takes a lot of memory to compute them. Therefore, I think we should through it out, but I'm not sure. What do you think?

**Comment by miykael** [comment]
And a last comment. I once had one node for each figure creation and the workflow started to be very cluttered. I still have one node for the report per pipeline, but I think it makes more sense to have a `create_report.py` script that checks the folder structure (i.e. if `preproc_anat` is there or not) and than create the html file with the according figure links.
Like this we could just have a "run report script/node" function somewhere in the notebook.

**Comment by miykael** [comment]
This issue was connected to an earlier version of `fmriflows`. A report file is now included but can receive a lot of love to look nicer. Will close this issue for now.
