### ISSUE TITLE
Error after pulling 

### ISSUE THREAD

**Issue by limbicode214** [miykael/fmriflows#36]
Hi there

After pulling the fmriflows docker and the command:
 docker run -it --rm -p 9999:8888 -v /persistent/home//myHome/example:/data miykael/fmriflows 

I get the error message: 
/neurodocker/startup.sh: line 9: jupyter notebook --port=8888 --no-browser --ip=0.0.0.0 --NotebookApp.token=fmriflows: command not found

thanks for help!
mike

**Comment by PeerHerholz** [comment]
Hi @limbicode214,

thx for bringing this to our attention and sorry for the late reply.

I just checked it on my end and get the same error. @miykael I think the problem is the `activation`/`deactivation` of the `conda environments`. It seems that the container is starting in the default `conda environment` that doesn't include `jupyter` and not the `neuro` one from which the `notebooks` should be started from.

Cheers, Peer

**Comment by miykael** [comment]
Hello @limbicode214,

Thank you for pointing to the issue, and thanks @PeerHerholz for reiterating on it. It took me a few days to find the bug, but at the end it was due to some small `Dockerfile` issue [here](https://github.com/miykael/fmriflows/commit/8bf19f6f49268e2528d4a8d1113020463bd3ce4e#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L260).

I've updated the code and the docker image, so everything should work again as before. @limbicode214, the command `docker run -it --rm -p 9999:8888 -v /persistent/home//myHome/example:/data miykael/fmriflows` should now work.

Cheers, Michael
